#!/bin/bash -e
#
# ==============================================================================
# PAQUETE: canaima-estilo-visual-iconos-gnome
# ARCHIVO: postinst
# DESCRIPCIÓN: Configura el sistema despues la instalación del paquete.
# COPYRIGHT:
#  (C) 2010 Luis Alejandro Martínez Faneyth <martinez.faneyth@gmail.com>
#  (C) 2010 Diego Alberto Aguilera Zambrano <daguilera85@gmail.com>
#  (C) 2010 Carlos Alejandro Guerrero Mora <guerrerocarlos@gmail.com>
#  (C) 2010 Francisco Javier Vásquez Guerrero <franjvasquezg@gmail.com>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

PKG="canaima-estilo-visual-iconos-gnome"

case ${1} in

	configure)
	;;


        abort-upgrade|abort-remove|abort-deconfigure)
        ;;

        *)

                echo "postinst no reconoce el argumento '"${1}"'" >&2
                exit 1

        ;;

esac

#DEBHELPER#

#set -e

#write_cache()
#{
#if [ -x /usr/bin/gtk-update-icon-cache ]; then
    #if ! gtk-update-icon-cache --force --quiet /usr/share/icons/gnome; then
        #echo "WARNING: icon cache generation failed"
    #fi
#fi
#}

#if [ "$1" = "triggered" ]; then
    #write_cache
    #exit 0
#fi

#SIZES=$(ls /usr/share/icons/canaima-iconos/*/places | sed -rn 's,^.*/([0-9]+)x[0-9]+/.*$,\1,p')

#( while read name prio; do
    #command="update-alternatives --install /usr/share/icons/canaima-iconos/places/scalable/start-here.svg start-here.svg /usr/share/icons/gnome/scalable/places/$name.svg $prio"
    #for s in $SIZES; do
      #command="$command --slave /usr/share/icons/gnome/${s}x${s}/places/start-here.png start-here-${s}.png /usr/share/icons/gnome/${s}x${s}/places/$name.png"
    #done
    #$command
  #done ) << EOF
#debian-swirl 30
#gnome-foot 20
#swirl-foot 20
#EOF

#write_cache

exit 0
