#!/bin/sh -e

CURSORES_VIEJOS = "/usr/share/icons/canaima-cursor"
ICONOS_VIEJOS = "/usr/share/icons/Oxygen-Green-Canaima"

case "$1" in

	install)
		
		if [ -e ${CURSORES_VIEJOS} ]
		then

			rm -rf ${CURSORES_VIEJOS}

		fi
		
		if [ -e ${ICONOS_VIEJOS} ]
		then

			rm -rf ${CURSORES_VIEJOS}

		fi
	;;
esac
