#!/bin/bash -e
#
# ==============================================================================
# PAQUETE: canaima-estilo-visual-iconos-gnome
# ARCHIVO: prerm
# DESCRIPCIÓN: Prepara el sistema para que el paquete sea removido.
# COPYRIGHT:
#  (C) 2010 Luis Alejandro Martínez Faneyth <martinez.faneyth@gmail.com>
#  (C) 2010 Diego Alberto Aguilera Zambrano <daguilera85@gmail.com>
#  (C) 2010 Carlos Alejandro Guerrero Mora <guerrerocarlos@gmail.com>
#  (C) 2010 Francisco Javier Vásquez Guerrero <franjvasquezg@gmail.com>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

PKG="canaima-estilo-visual-iconos-gnome"

case ${1} in

	remove|upgrade|deconfigure)
	;;

	failed-upgrade)
	;;

	*)

		echo "prerm no reconoce el argumento '"${1}"'" >&2
		exit 1
	;;

esac

#DEBHELPER#
set -e

if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ] ; then
  for name in debian-swirl gnome-foot swirl-foot; do
    update-alternatives --remove start-here.svg /usr/share/icons/canaima-iconos/places/scalable/$name.svg
  done
  rm -f /usr/share/icons/gnome/icon-theme.cache
fi

exit 0
